### ISSUE TITLE
HR dataset

### ISSUE THREAD

**Issue by Afshinshafei** [mantariksh/231n_downscaling#2]
Thanks again for your work! :) 
i had another question about the dataset. you mentioned you downloaded the high resolution 1km dataset from "ERFACS. World climate research programme.". I wanted to ask is it free to download such data from this platform? or how can we obtain this dataset from it.
thank you for your time.

**Comment by sonjaove** [comment]
this might not answer your question, but 

the hr data is usually hard to get, you dont really get ready made pairs of lr and hr for climate related tasks(as a cv model would demand), specifically precipitation due to various reasons, so the trick that is usually applied is to down-sample and up-sample the data you already have to match the dimensions you want.

the dataset that solves the problem though is [rainnet](https://github.com/neuralchen/RainNet), it is a good source and has some rich data.
